### ISSUE TITLE
[CSNG] Pre6 Write Access Disabled in Dev Mode

### ISSUE THREAD

**Issue by t00fatt** [htruong/crankshaft#206]
- What crankshaft version?
NG Pre6
- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always reproducible.
Clean install
Boot into dev mode
no write access
use CMT filesystem boot unlock, "done" returned
still no write access on boot

I can not enable write access on either boot or system in dev or debug mode after updating to Pre6. Worked perfectly in Pre5 with write access in dev mode on boot.

[debug.zip](https://github.com/opencardev/crankshaft/files/2300840/debug.zip)

**Comment by hawkeyexp** [comment]
Tried with the published build - all ok. Log seems also clean.
I only had this problem one time a while ago which was caused by a corrupted fs on /boot.
I updated csmt and added a more clean output with state before and after remount and a check option for boot.
Update it in dev mode with:
`crankshaft update csmt`
Run:
`crankshaft filesystem boot check`

**Comment by t00fatt** [comment]
Could it be my SD card? I updated over USB from Pre5 to Pre6 and couldn't get write access. Then I did a clean wipe and flash of Pre6 and still couldn't get write access. I had wiped Pre6 and flashed Pre5 again before seeing your message, but never booted it. Wiped and reflashed again with Pre6, and I have write access again in dev mode and Pre6.

**Comment by hawkeyexp** [comment]
Possible a demanged sd but also possible only it was an fs fail.
