### ISSUE TITLE
day / night switch

### ISSUE THREAD

**Issue by VittorioLu** [htruong/crankshaft#218]
Hello,
I would like the night / day switching to be done by BH1750
light sensor, convenient for tunnels and cloudy days. it can be done ?

**Comment by hawkeyexp** [comment]
Starting with pre8 the csmt got the option to set system state - curently you have to release it with custom code. But note: openauto won't switch to dark gui while phone is connected and state is switching caused by code limitations which can be hopefully solved in future.

`crankshaft state day|night`
