### ISSUE TITLE
Android Auto Crashes after 5 Seconds since the 6. January update

### ISSUE THREAD

**Issue by HoLy1337** [htruong/crankshaft#291]
Hey,

I updated to the 6 January version, but now when I connect my phone Android auto starts and crashes then directly after 3-6 seconds...
Then I'm back on the crankshaft screen... The USB button says there is a USB connection, but when I click on it it don't opens Android auto again.
When I unplug my phone and connect again the same happens again.
One-time I became a communication error 12 on my phone.

- What phone do you have?
Pixel 2
- What OS version?
Android 9 January update

- What crankshaft version?
January 6

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.

Allways since this update
- Please provide any further information that you might find helpful if available.

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.

  Warning: if you have configured wifi passwords they will be blanked by script during creation.
  We can't make absolutly sure you passwords are removed so do a personal check of the files inside the zip.

**Comment by hawkeyexp** [comment]
Add a debuglog - without i can't help

**Comment by roan111** [comment]
I have the same problem with the OnePlus 6, tommorow i post the debuglog

**Comment by roan111** [comment]
> Add a debuglog - without i can't help

I have the same problem with a OnePlus 6 device

[debug.zip](https://github.com/opencardev/crankshaft/files/2759800/debug.zip)

[debug (AA crashed).zip](https://github.com/opencardev/crankshaft/files/2760022/debug.AA.crashed.zip)

**Comment by hawkeyexp** [comment]
Thx for the logs... In general it looks fine and aa is starting the normal way - but it happens a communication timeout in aasdk which causes the exit. I will have a look to it but in this part of code i can't do anything. I will check if something is causing a higher load etc. which can possible force a timeout.

**Comment by roan111** [comment]
Ok thanks i hope that it is possible to fix the problem

**Comment by cydia2020** [comment]
~~This has nothing to do with OpenAuto nor crankshaft, Google screwed up again.~~
The information stated above is **NOT CORRECT**, AA works fine with an OEM or third party Google authorized HU

Opt out from the beta version of Google Play Services *temporarily* fixes the issue as of the date of original comment. However as of 4/2/2018 GMS is officially 15.0.90, and the issue persists on Crankshaft.

**Comment by roan111** [comment]
> This has nothing to do with OpenAuto nor crankshaft, Google screwed up again.
> 
> Opt out from the beta version of Google Play Services, reinstall the last stable version from Apkmirror. Fixed my issue.
> 
> Edit: please install GMS version 14.8.47

Thanks after the downgrade of GMS android auto is working normally

**Comment by hawkeyexp** [comment]
thx @cydia2020 for the hint ...
@roan111 i will close now.

**Comment by HoLy1337** [comment]
Need some time to downgrade but now it works

**Comment by tsukisan** [comment]
Can we get a "Known Issues" section in the wiki for info such as this? I had to dig a bit to find this as I am also having this problem. Closed tickets isn't the best archive IMO.

**Comment by hawkeyexp** [comment]
Can you check if this build of openauto is working for you? The timeout is a thing with not identified reason - only happening on some devices not general...
Replace the file in /usr/local/bin with the new one and report back please.
ftp://cloud.hawknetwork.de/FTP/autoapp

**Comment by dmosleyx** [comment]
I am not signed up for Beta on any of my accounts but this started happening yesterday. Same issue, exactly five seconds, every time. 

I did re-check and verify my non-beta status just in case. I also went ahead and cleared all caches. Still does it, like clockwork.

**Comment by breakingspell** [comment]
Encountering this as well (alpha 3), looks like Play Services 15.0.90 is the stable version now. 
I replaced /usr/local/bin/autoapp (forgot to set +x permissions for a second, lol), but the issue persists. The system updater pops up to address the different openauto binary too, super slick interface!

Here's my debug logs on the autoapp version you provided. 
[debug.zip](https://github.com/opencardev/crankshaft/files/2820067/debug.zip)

**Comment by cydia2020** [comment]
Having the same issue now as well since Play Services is now officially 15.0.90, will try on my OEM head unit later today to see if the same thing happens.

Should consider reopening it

**Comment by cydia2020** [comment]
Downgraded to Alpha 1, but the issue is presists. Crankshaft times out exactly after 5 seconds.

Device is a Pixel XL, with Google Play Services 15.0.90

**Comment by tsukisan** [comment]
Same issue on my pixel XL:
Google play services 15.0.88
Android Auto app version: 3.9.585064-release
OS version: 9

My wife's Galaxy S8+ is working fine:
Google play services 14.7.99
Android Auto app version: 3.9.585064-release
OS version: 8

Both are being used on the same pi 3 (not simultaneously) running Alpha 3

**Comment by cydia2020** [comment]
Doesn't work on Nexus 5X neither.

Attached log file was captured from my Pixel XL

[dmesg_log.txt](https://github.com/opencardev/crankshaft/files/2825349/dmesg_log.txt)
[gearhead_log.txt](https://github.com/opencardev/crankshaft/files/2825350/gearhead_log.txt)

It seems like these two parts are extremely suspecious
[suspicious_log.txt](https://github.com/opencardev/crankshaft/files/2825354/suspicious_log.txt)

As they appear right before the connection drops out (or OpenAuto crashes)

@hawkeyexp should be reopened

**Comment by cydia2020** [comment]
Hmmmmmm


02-03 20:01:48.872 28371 28371 D GH.ConnLogger: Connectivity event: USB_CHARGER_DISCONNECTED Session ID: 5f291075-14f7-4ebc-a95e-7b9eebd215e3 Event Index: 2
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: IO exception
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: java.io.IOException: read failed: EIO (I/O error)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at libcore.io.IoBridge.read(IoBridge.java:511)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at java.io.FileInputStream.read(FileInputStream.java:307)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at nte.run(:com.google.android.gms@15090037@15.0.90 (100400-231259764):7)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at libcore.io.Linux.readBytes(Native Method)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at libcore.io.Linux.read(Linux.java:184)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:254)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	at libcore.io.IoBridge.read(IoBridge.java:501)
02-03 20:01:48.872  2644 24735 D CAR.GAL.GAL: 	... 2 more
02-03 20:01:48.873 24123 24139 E adbd    : aio: got error event on read total bufs 1: Cannot send after transport endpoint shutdown
02-03 20:01:48.873  2644  2644 W CAR.SERVICE: Critical error 3 detail: 52 msg: io error
02-03 20:01:48.873 24123 24139 E adbd    : remote usb: read terminated (message): Cannot send after transport endpoint shutdown
02-03 20:01:48.881  2644  2644 D CAR.SERVICE: onCarDisconnected
02-03 20:01:48.881  2644  2644 D CAR.SERVICE: tearDownCarState
02-03 20:01:48.883 24123 24123 I adbd    : closing functionfs transport
02-03 20:01:48.893   896   940 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
02-03 20:01:48.896  2644  2644 D CAR.SERVICE: notifying car connection listeners of disconnection, clients:4

**Comment by rubenverhoef** [comment]
Same problem since today for me, AA is starting and after 5 sec it goes back to openauto main screen (with lock icon at upper left)
This is since my phone updated the Google play services to 15.0.90...
Maybe the AA protocol has changed? Does anyone know if there is any documentation about it?

**Comment by crstmkt** [comment]
Same problem here. AA starts but quits after 5 sec.

Phone: Nokia 6.1 (2018)
OS: Android Pie
AA version: 3.9.585064-release
CS Version: Alpha 3

**Comment by Kman91** [comment]
Same problem with me now.  Crankshaft was working beautifully, but today it will not connect for more than 5 seconds.  I upgraded to the latest release (Alpha 3), but still the same issue.

I love Crankshaft and use it every day (and thanks for all of you who did such great work to make this available!).  Now it won't work at all.  This is very bad.

I would be happy to provide any files, but while I'm experienced with hardware, I'm an Android file newbie.  If someone could point me to the files I should provide I'll be super grateful!  I'll try to find them myself too.

Rpi: 3B+
Phone: Samsung Galaxy S8 (unmodified)
OS: Android 8.0.0
AA version: 3.9.585064-release
CS Version: Alpha 3
Google Play services: 15.0.90

I just reloaded 11/24 code (pre Alpha) and the problem is just as bad.  Argghh.

**Comment by Kman91** [comment]
Sounds like a bunch of people have this problem. https://www.reddit.com/r/crankshaft/comments/ant3xt/crashing_shortly_after_i_plug_in_my_phone/ 
Seems like we should definitely reopen this issue.  Thanks!

**Comment by yusijs** [comment]
The fix needs to come from openauto, not crankshaft - see https://github.com/f1xpl/openauto/issues/157

@hawkeyexp might consider opening this again for tracking purposes?

**Comment by theelichtje** [comment]
Yup, same issue started this morning for me aswell.

Tried the latest 3 alpha versions, all the same issue. Trying to downgrade play services right now.

**Comment by Aaron407s** [comment]
The same issue is happening for me as well. Has anyone found a viable and persistent downgrade option for Google Play Services?

**Comment by tsukisan** [comment]
FYI, there are no known fixes for this and it is happening to anyone who's device (phone/tablet, not pi/crankshaft) has been updated to Google Play Services 15.0.9+ (I believe) and downgrading is temporary, at best.

Hawkeyexp identified that this problem is on Google's side and that it couldn't be fixed without Google's involvement.

I'm sure everyone is doing everything they can to get this working again, however, I don't think that notifying them that your phone isn't working isn't going to help the process. The way things are going, all phones still receiving OS updates will likely stop working at some point unless this gets resolved on Google's end (or maybe in the base OpenAuto software as they seem to have identified a fix or workaround).

So for now let's leave this thread quiet unless you have new information to add (update to GPS, phone starts working unexpectedly, etc.).

**Comment by yusijs** [comment]
@tsukisan this is *not* googles fault. The problem lies solely with the opensource version of OpenAuto. Google changed an api that openauto started depending on. Openauto uses this api to listen for a "handshake", and when this handshake doesnt arrive, openauto assumes the app has crashed. Removing this handshake breaks wireless connection, but would "fix" usb connections. 

Please don't post false information.

Edit:
The fix/workaround is in this thread -> https://github.com/f1xpl/openauto/issues/157#issuecomment-461535771

**Comment by Aaron407s** [comment]
Apologies for adding another post, but is there any chance that a temporary build could be posted per the post above that incorporates the USB workaround for the time being? I'm unfortunately lacking in the modifying/recompiling background...

**Comment by rubenverhoef** [comment]
> Apologies for adding another post, but is there any chance that a temporary build could be posted per the post above that incorporates the USB workaround for the time being? I'm unfortunately lacking in the modifying/recompiling background...

You can make a pull request and a owner of cs can merge it. @hawkeyexp is busy right now with personal stuff so he will not be available for some time. When I find some time I will do it but that will be in a few days. This code change can be done in openauto only so update can be pushed OTA without full system upgrade.

**Comment by reganface** [comment]
For anyone still having this issue, the issues module on the openauto repository has been removed, so the workaround linked above by @yusijs is now just a 404.  There is, however, a pull request which fixes the issue, but has yet to be merged.  I tried it and it work for me!  The fork is located here: https://github.com/Oper92/openauto

**Comment by parkerlreed** [comment]
>the issues module on the openauto repository has been removed

Why am I not surprised. I knew going paid for Pro was a mistake. OSS never got touched again.

**Comment by yusijs** [comment]
@parkerlreed yeah, damn him for wanting to earn something from his work. If OSS had been sustainable your complaint would be valid, but being upset at one guy for not wanting to build shit for free doesnt really fly imo.

**Comment by miguelpppires** [comment]
> For anyone still having this issue, the issues module on the openauto repository has been removed, so the workaround linked above by @yusijs is now just a 404. There is, however, a pull request which fixes the issue, but has yet to be merged. I tried it and it work for me! The fork is located here: https://github.com/Oper92/openauto

Hey i know this isn't probably the right place to post, but since openauto has no issue tracker i thought i might try my luck here... i've updated the file that changed with the new code, do i need to compile it again? can you guide me through the next steps?

**Comment by parkerlreed** [comment]
@MikeStardust yeah you would just compile it as normal (assuming you updated the file in the actual source code checkout)
