### ISSUE TITLE
Automatic connection with bluettoth

### ISSUE THREAD

**Issue by WhereisBielefeld** [htruong/crankshaft#303]
- What phone do you have?
Oneplus 6

- What OS version?
9.0x

- What crankshaft version?
latest

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Always repoducible

I am not whether this is a bug or a missing setting, but when i start Crankshaft with bluetooth, i have to manual connect it by chosing it from my list of bluetoothdevices. Does it have to be that way or is there a way to connect both (Phone/Crankshaft)  right after start without doing it manualy?

Best regards,

**Comment by SergioMuinhos** [comment]
What raspberry pi do you use? I know that in the last Raspberry Pi 3B + the bluethoot is much more modern than that of the normal 3 B, I also have that problem and solve it quickly, Buy an NFC tag and I stuck it in the car and when I step over I make all the necessary bluethoot connections, The application I have used is called NFC Tools and you can find it in the Play Store.
I hope it has helped you. regards

**Comment by hawkeyexp** [comment]
english please !

**Comment by hawkeyexp** [comment]
CS should auto connect to pired bt devices during startup. Try following please:

Clear paired devices on cs side.
remove paired device on phone side.
restart both
pair your phone again.
Make a cs reboot via gui to ensure the paired states is successfully stored on cs side.

**Comment by hawkeyexp** [comment]
long time inactive - closing...

**Comment by basemhegazy** [comment]
I've managed to get the handsfree working (external BT dongle), calling is working perfectly (send/receive) however the bluetooth is not autopair/autoconnect after reboot, all paired-devices  get lost and I have to go through the process from the start.

What phone do you have?
Huawei Y5 Prime 2018

What OS version?
Oreo 8.1

What crankshaft version?
latest (2019-08-08)

Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Always reproducible (everytime I reboot the Pi)
