### ISSUE TITLE
Feature: Remove all messages during boot, for a more factory look

### ISSUE THREAD

**Issue by rcrichton** [htruong/crankshaft#35]
It would be great if we could display a splash screen or at least no messages during boot. This would make the bootup look better for use day to day. Of course in dev mode those messages may be useful however, outside of dev mode they shouldn't be necessary.

Perhaps something like this would help: https://raspberrypi.stackexchange.com/questions/59310/remove-boot-messages-all-text-in-jessie/59311

**Comment by EveAeternam** [comment]
Quick suggestion: what about modifying the splash script? It could display the crankshaft splash image, then if the user wants, an optional one that could match their car model or etc.

**Comment by jlukanc1** [comment]
This could be done similar to how Raspbian Pixel has the splash screen, just add the ability to change it and maybe add a few premade splash screens.

**Comment by htruong** [comment]
That'd be possible. There is already a pull request in, I will review it and merge. This weekend will be the development/testing/refine weekend :)

**Comment by htruong** [comment]
Done!

**Comment by Richard6360** [comment]
How is this archieved ?? I stil have boot text messages in cs-ng alpha

**Comment by hawkeyexp** [comment]
usually you will only see the splash -. only if something  is triggered like dev mode, sound device missing etc. the splash will be hidden to show the notify.

**Comment by Richard6360** [comment]
I did a new instal.Al I see is okNo warnings I believe.Is there an option to show the splash in stead of message?
-------- Oorspronkelijk bericht --------Van: hawkeyexp <notifications@github.com> Datum: 29-01-19  19:25  (GMT+01:00) Aan: opencardev/crankshaft <crankshaft@noreply.github.com> Cc: Richard6360 <richard6360@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [opencardev/crankshaft] Feature: Remove all messages during boot, for a more factory look (#35) 
usually you will only see the splash -. only if something  is triggered like dev mode, sound device missing etc. the splash will be hidden to show the notify.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opencardev/crankshaft","title":"opencardev/crankshaft","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/opencardev/crankshaft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hawkeyexp in #35: usually you will only see the splash -. only if something  is triggered like dev mode, sound device missing etc. the splash will be hidden to show the notify."}],"action":{"name":"View Issue","url":"https://github.com/opencardev/crankshaft/issues/35#issuecomment-458651649"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opencardev/crankshaft/issues/35#issuecomment-458651649",
"url": "https://github.com/opencardev/crankshaft/issues/35#issuecomment-458651649",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hawkeyexp** [comment]
Add a video and debuglog please...
